### ISSUE TITLE
Lead Capture Form - confirmation box - Empty

### ISSUE THREAD

**Issue by rohitmanglik** [EduGorilla/EduMatch#261]
In Lead Capture Form, confirmation box has no value:

![image](https://user-images.githubusercontent.com/677634/27271530-e560eb62-54e2-11e7-9862-fb3cf591b3b5.png)

**Comment by rohitmanglik** [comment]
Error no more present.

**Comment by rohitmanglik** [comment]
@181514912 please close it if the issue is no more reproducible.

**Comment by 181514912** [comment]
Is working fine.
