### ISSUE TITLE
Conflict in filters of Archieve page

### ISSUE THREAD

**Issue by rohitmanglik** [EduGorilla/EduMatch#278]
In Archieve page, dropdown of filters are not working when EduMatch is active.

Probably there is some JS conflict.

Sample Archieve page: http://stg3.edugorilla.com/listing-category/it-computers/

**Comment by 181514912** [comment]
There was a conflict between bootstrap.min.js in fetch_dependencies.php which was already solved by the commit c6ee37b (either use is_page() or use admin_enqueue_scripts). The issue is fixed.
